### ISSUE TITLE
NHL 2K2: Tiny menus ingame

### ISSUE THREAD

**Issue by Shoegzer** [libretro/flycast#114]
Upon starting a game and pressing "start" to see the menu, it's rendered at about 50% of the size it should be:

![nhl](https://user-images.githubusercontent.com/12475371/42232006-284b561c-7ebb-11e8-9eaf-b29cc78c69dc.png)

Oddly, this does NOT occur in other Sega Sports games.  @flyinghead, or @twinaphex any ideas what's going on here?

Also, the game itself freezes when a goal is scored.  I'm not convinced they aren't related yet, so I'll hold off from submitting a new issue for that, for now.

Tested on linux x64, kernel 4.15, commit 20c509c65d0d92704dbe7d25d9ac714fc056363e

**Comment by flyinghead** [comment]
I can confirm the abnormally small size of the Start menu.
However the game didn't crash when the other team scored a goal, which took quite some time. I couln't score a goal myself...

I'm seeing lots of `Error in /home/raph/t/shell/linux/../../core/hw/sh4/sh4_mmr.cpp:WriteMem_P4:417  -> Write to P4 not implemented - addr=e43e24bc, data=35353535` around the time the VMU is accessed.

**Comment by flyinghead** [comment]
No crash when I score either.

**Comment by Shoegzer** [comment]
Hmm thanks @flyinghead.  That might have been a one-time issue on my end, I've had that happen before, though rarely.  I'll try another goal when I have more time.

**Comment by flyinghead** [comment]
I think the pause menu being rendered smaller than it should has now been fixed.
It's due to extreme Z values so it might depend on your GPU/driver.

Please retest.

**Comment by Shoegzer** [comment]
Thanks @flyinghead, tested and the menu looks fine now.  

With that said, I discovered a separate issue with this game: some "selection box" items are blacked out so you can't see what's inside them.  

![screen1](https://user-images.githubusercontent.com/12475371/49318270-e7d48780-f4c5-11e8-9037-1f81b2582eb1.png)

Compare with [this video](https://youtu.be/3gy4EnnC0UE?t=9) about 10 seconds in, taken from the same game running on a real Dreamcast.

If necessary I can close this issue and open a separate one, or just leave this as-is.  Your call, just let me know.  Thanks again.

**Comment by flyinghead** [comment]
I noticed this problem as well. Let's keep this issue open as I think it's related.

**Comment by flyinghead** [comment]
The black VMU menu should be fixed as of a45420ff27d7382dee8176817eda4efa86cc1157

**Comment by Shoegzer** [comment]
Thanks @flyinghead, but I'm still getting the same black screen unfortunately.  Tested with a45420f.

**Comment by flyinghead** [comment]
Please check you have the core option Extra Depth Scaling set to Auto.
What graphic card do you have?
Also I believe this only happens with the per-pixel renderer, not with per-triangle or per-strip. Can you confirm this?

**Comment by Shoegzer** [comment]
Ah yes, once I set Extra Depth Scaling to "Auto" the menu looks fine (and yes, confirmed the issue only occurs with the per-pixel renderer).  We're not quite there yet, however.  Whie most menus now look fine, if you leave Extra Depth Scaling at "Auto" then start an actual game, then push Y to call the "help" popup, the following occurs, though again **only** with the per-pixel renderer:

Per-pixel:
![2](https://user-images.githubusercontent.com/12475371/49472473-88d08480-f7dd-11e8-995e-130d47b950b3.png)

Per-triangle:
![1](https://user-images.githubusercontent.com/12475371/49472487-8ff79280-f7dd-11e8-8bd7-9c81044c9d5c.png)

I should note that turning Extra Depth Scaling from "Auto" to "On" (and with per-pixel) fixes the above, however other menus such as the VMU are dark.  Maybe the "Auto" logic needs to detect when to scale depth more accurately?

Test system is an Nvida GTX 1070M with 390.77 driver.

**Comment by Shoegzer** [comment]
Just tested this and all issues seem to be fixed, nice job.

@flyinghead not to bring this one back from the dead, but is there any reason to set  "Extra Depth Scaling" to anything other than "Auto", and if not, would you consider removing the option at some point?

**Comment by flyinghead** [comment]
Thanks for the feedback.

You're right that this option shouldn't be exposed and I will remove it at some point.

**Comment by Shoegzer** [comment]
Thanks @flyinghead, and as always, really well done tracking this down and resolving it.  I'm sure it wasn't easy.
