### ISSUE TITLE
Save States Crashing Reicast when I Re-Enter Reicast after Save Stating 

### ISSUE THREAD

**Issue by TradeDraft** [libretro/flycast#287]
**Description of the Issue**

When I save state it will let me load but when come back to Retroarch it Crashes when I try load Save State

**Description**

When I save state it will let me load but when come back to Retroarch it Crashes when I try load Save State
Expected behavior

**Load the Save State Normally**
Actual behavior

**Crashes Retroarch
Steps to reproduce the bug**

    1.Save State in Dreamcast Game(Shenmue)
    2.Exit Retroarch
    3.Start up Retroarch
    4.Load Game Up
    5.Press Load State Button
    6.Then Crashes

**Bisect Results**

[Try to bisect and tell us when this started happening]
Version/Commit

**You can find this information under Information/System Information**

    1.7.4 and Latest Nightly 1.7.5 Versions

**Environment information**

    OS: Windows 10 64 it
    Compiler: [In case you are running local builds]

**Comment by inactive123** [comment]
Can you specify the game you are using?

**Comment by inactive123** [comment]
This might be of interest to @RetroSven in case it' something we can reproduce.

**Comment by TradeDraft** [comment]
> Can you specify the game you are using?

Was Playing Shenmue.

I have log for the Crash

**Comment by RetroSven** [comment]
Did this happen just once or are you able to reproduce every time? (And how many times have you tried?)  

Does it happen just with Shenmue?  If you haven't tried any other games, please do so.

Please also attach your RA log file (posted to something like pastebin.com)

**Comment by TradeDraft** [comment]
> Did this happen just once or are you able to reproduce every time? (And how many times have you tried?)

Has Happened a Few Times

> Does it happen just with Shenmue? If you haven't tried any other games, please do so.

Did with HeadHunter but it seemed to fixed it self when I ran/used the Debug File

> Please also attach your RA log file (posted to something like pastebin.com)

Here is link to Log:

https://pastebin.com/vEWPjusg

**Comment by RetroSven** [comment]
Are you sure that's the entire log?  Does that log capture the crash event?
When you say "press load state button" do you mean you press F2 or have you configured load-state to a particular button combo?  If the latter, please provide more detail.

Has this ever worked for you in any version or is this your first time trying save states in reicast?

**Comment by RetroSven** [comment]
sorry not f2 - f4

**Comment by Siushaga** [comment]
I also have same issue. Have tried with Sonic Adventure, Phantasy Star Online (offline mode), Grandia II, to name a few. Latest Android nightly build is what I was working with and 1.7.5 RetroArch.

**Comment by RetroSven** [comment]
Have both of you tried loading the state via both in-game and via the menu?

**Comment by Siushaga** [comment]
Did some more testing. Seems if I let the game load all the way in (past Dreamcast/Sega logos, etc) then loading from save state will work. If it's doing the boot screens and try to load state then app force closes.

For good measure, I deleted save state and then updated core for any new pushes recently before creating a new save state and closing game to reopen for the test. Not sure if that made a difference or not too.

**Comment by TradeDraft** [comment]
> Are you sure that's the entire log? Does that log capture the crash event?

That what I got it's the Whole Log File

> When you say "press load state button" do you mean you press F2 or have you configured load-state to a particular button combo? If the latter, please provide more detail.
> 
> Has this ever worked for you in any version or is this your first time trying save states in reicast?

Pretty Much did when I started using it. I did update Core and RetroArch when I checked that the Nightly Version did not Crash

> Have both of you tried loading the state via both in-game and via the menu?

Just In Game at the Moment

**Comment by RetroSven** [comment]
@TradeDraft did you see Siushaga's comment?  Have you tried that?

**Comment by TradeDraft** [comment]
> @TradeDraft did you see Siushaga's comment? Have you tried that??

Yes I did but I tried another Save State and Seems to be Working Now. Even works when just Loading the Game Up.

Have Updated to latest Working Retroarch Nightly Version that Works and Up To Date Reicast and seems to be working.

Keep Testing to see **IF** it's Fixed

**Comment by Eds1989** [comment]
I use auto load states, and too get this issue.

When I try to load any game that has previously had a save state created, RetroArch automatically tries to load the last save state when starting a game. I can reproduce this reliably.

If I go to my states folder, and delete the corresponding savestate.auto file, the game will then load correctly.
I have not tried turning this off and using manual save/load yet, as I like auto load ;)

Does anyone want logs as I can get these if required to raise as a bug.

**Comment by RetroSven** [comment]
@Eds1989 instead of deleting the savestate.auto file can you try copying it to one of the numbered save states and then try to manually load it?  This is to check to see if the data in the file is valid.

**Comment by Eds1989** [comment]
So I renamed the .auto to .state1, closed retroarch, loaded the same game and loaded state 1.
It loaded fine.

I closed the content, at which point an auto savestate file gets generated. If I try to start the game, it fails, and I start to see some "Unhandled Access" errors.

**Comment by Eds1989** [comment]
Might not actually be Dreamcast specific, as I have just found the same behaviour to be true for GoldenEye on Mupen64.

Same thing, when it tries to load .auto it fails, but if renamed to state1, a manual load works fine.

**Comment by RetroSven** [comment]
this is likely related to RA trying to load too early - before the core has had a chance to properly initialize - will try to take a look this weekend.
@Eds1989 are you using the most recent nightly build of both RA and reicast?

**Comment by Eds1989** [comment]
I'm just using the 1.7.5 release, as I'm assuming to use nightlies I would have to compile myself, which I am unfamiliar with (not a developer 😢 )

As for Reicast, I'm using 0.1 35ad30b which I believe to be the latest as I just updated the core just now and the version didn't change.

**Comment by RetroSven** [comment]
@Eds1989 no need to compile - you can grab all the very latest compiled cores/RAs here (go up one directory if you're using something besides windows):

https://buildbot.libretro.com/nightly/windows/

**Comment by Eds1989** [comment]
Ok have just installed 19-10-18, and same issue is present there too.
Just ran a Dreamcast game for a few minutes, closed content, loaded the game again and it crashes RetroArch back to the desktop.

**Comment by TradeDraft** [comment]
I have found on Saturday the Problem is Back.

Every Load State I try and Load a Save State it make Retroarch Crash every time.

Using Latest Core and Stable Release of Retroarch 1.7.5

**Comment by flyinghead** [comment]
The format of reicast save states has changed recently and attempting to load an "old" save state will very likely crash the core and RetroArch.
However you should be able to save and then load a new save state.

**Comment by RetroSven** [comment]
@flyinghead there is a "version" field in the save states that can be used for these kinds of format changes - do you have the specifics of what changed handy (or know which git commits relate to these new changes)?   I think something can be done so that people can still load their old states.

**Comment by RetroSven** [comment]
@flyinghead nvm - I see the maple changes

**Comment by flyinghead** [comment]
Right.  I might have changed the format more than once in all the maple changes but we can probably ignore it and only consider before and after

**Comment by TradeDraft** [comment]
@flyinghead when did the Format Change?

As It been about around a Week or since I last made the Latest Save State I was using with Shenmue.

Though I tried save state last night with Dynamic Cop and that Worked Fine

**Comment by TradeDraft** [comment]
Is there way to Convert from Old to New Save Style Format?

**Comment by flyinghead** [comment]
This should help once it's merged: https://github.com/libretro/reicast-emulator/pull/353

The Save State format change occurred on Oct 12.

**Comment by flyinghead** [comment]
Another change related to save states: #359 
Can you load your saved state now?

**Comment by TradeDraft** [comment]
Old Ones still Crash but one I saved today worked fine @flyinghead

**Comment by flyinghead** [comment]
Can you tell me the exact size of the Shenmue save state that you're trying to load? Also the date/time when it was created would be helpful too.

**Comment by flyinghead** [comment]
Another important note regarding older save states: the following core settings must be the same as when the save state was created: broadcast, region, cable, enable purupuru. The number of controllers must be the same and they should all be gamepads (no light gun, mouse, keyboard)
These limitations do not apply to newer save states.

**Comment by TradeDraft** [comment]
> Another important note regarding older save states: the following core settings must be the same as when the save state was created: broadcast, region, cable, enable purupuru. The number of controllers must be the same and they should all be gamepads (no light gun, mouse, keyboard)
> These limitations do not apply to newer save states.

I just Keep them at Default

> Can you tell me the exact size of the Shenmue save state that you're trying to load? Also the date/time when it was created would be helpful too.

Here are the Save States I used Zipped Up here:

https://www.sendspace.com/file/2a0l1n

**Comment by Eds1989** [comment]
> this is likely related to RA trying to load too early - before the core has had a chance to properly initialize - will try to take a look this weekend.
> @Eds1989 are you using the most recent nightly build of both RA and reicast?

I suspect my auto save/load issue is likely unrelated? Should I therefore open a new issue on this?

**Comment by flyinghead** [comment]
@TradeDraft  thanks for the file. I'll have a look at what I can do.
@Eds1989 auto load states have their own share of issues due to the early loading of the state. I've fixed several of these in my last commits but you might want to open a new issue to track any remaining problem.

**Comment by flyinghead** [comment]
@TradeDraft  These save states were created when several changes affecting save states were going on so I had to do a hack to load them. I saved them in the new format if you want to try:
https://www.sendspace.com/file/1jk4ci

**Comment by TradeDraft** [comment]
@flyinghead I tried the Save States but Sadly it's still Crashed.

Thanks for Trying
