### ISSUE TITLE
RetroArch Reicast crashing after loading a game on Windows.

### ISSUE THREAD

**Issue by blackman91** [libretro/flycast#309]
Using windows 7, retroarch latest nightly after updating the Retroarch reicast core, reicast crashes when loading any rom, I think the merge of oit and normal reicast may have caused it, it worked fine in previous build, here is a log:
[INFO] 	DEFAULT_ON 00
[INFO] Environ GET_VARIABLE reicast_vmu4_pixel_off_color:
[INFO] 	DEFAULT_OFF 01
[libretro INFO] File extension is: .gdi
[INFO] Environ SET_HW_RENDER.
[INFO] Requesting core OpenGL context (4.3).
[INFO] Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 44055.95 Hz.
[INFO] [Video]: Video @ 1920x1440
[INFO] [Video]: Using HW render, OpenGL driver forced.
[INFO] [GL]: Found GL context: wgl
[INFO] [GL]: Detecting screen resolution 1920x1080.
[ERROR] [WGL]: Failed to create core context. Falling back to legacy context.
[INFO] [WGL] extensions: WGL_EXT_depth_float WGL_ARB_buffer_region WGL_ARB_extensions_string WGL_ARB_make_current_read WGL_ARB_pixel_format WGL_ARB_pbuffer WGL_EXT_extensions_string WGL_EXT_swap_control WGL_EXT_swap_control_tear WGL_ARB_multisample WGL_ARB_pixel_format_float WGL_ARB_framebuffer_sRGB WGL_ARB_create_context WGL_EXT_pixel_format_packed_float 
[INFO] [WGL]: Adaptive VSync supported.
[INFO] [WGL]: wglSwapInterval(1)
[INFO] [GL]: Vendor: Intel, Renderer: Intel(R) HD Graphics 3000.
[INFO] [GL]: Version: 3.1.0 - Build 9.17.10.4229.
[INFO] [GL]: Using Core GL context, setting up VAO...
[INFO] [GL]: Using resolution 1912x988
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 430.
[INFO] Shader log: ERROR: 0:1: '' :  Version number not supported by OGL driver
ERROR: 3:1: 'in' :  supported in GLSL 1.30 or later 
ERROR: 3:1: 'in' :  supported in GLSL 1.30 or later 
ERROR: 3:1: 'in' :  supported in GLSL 1.30 or later 
ERROR: 3:1: 'out' :  supported in GLSL 1.30 or later 

[ERROR] Failed to compile vertex shader #0
[ERROR] Failed to link program #0.
[ERROR] GLSL stock programs failed to compile.
[ERROR] [GL]: Failed to initialize shader, falling back to stock.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 430.
[INFO] Shader log: ERROR: 0:1: '' :  Version number not supported by OGL driver
ERROR: 3:1: 'in' :  supported in GLSL 1.30 or later 
ERROR: 3:1: 'in' :  supported in GLSL 1.30 or later 
ERROR: 3:1: 'in' :  supported in GLSL 1.30 or later 
ERROR: 3:1: 'out' :  supported in GLSL 1.30 or later 

[ERROR] Failed to compile vertex shader #0
[ERROR] Failed to link program #0.
[ERROR] GLSL stock programs failed to compile.
[ERROR] [GL]: Shader initialization failed.
[ERROR] [Video]: Cannot open video driver ... Exiting ...
[ERROR] Fatal error received in: "init_video()"
[ERROR] failed_to_start_audio_driver
[libretro INFO] Using Recompiler

The same build is working fine on Android:
https://github.com/libretro/reicast-emulator/commit/86f371be385dc712f24353efbb3ab03788d89a87

**Comment by hostile1975** [comment]
Hi,
This is what I did and it worked for me :
1) Delete the 2 core (regular +OIT) and the info file corresponding
2) Update info file
3) Update core but be carrefull to download the "reicast_oit_libretro.dll.zip" core  and not the "Sega-Dreamcat/Naomi(Reicast)" core that dont work anymore.

**Comment by hostile1975** [comment]
Is it normal the info file (reicast_libretro) and the core (reicast_oit_libretro) don't have anymore the same name ?

**Comment by flyinghead** [comment]
The reicast_oit_libretro.dll (or .so) shouldn't be used anymore. See this:
https://www.libretro.com/index.php/reicast-libretro-and-reicast-oit-libretro-merged-into-one-what-you-need-to-know/

**Comment by flyinghead** [comment]
@blackman91 This is due to the reicast core now requesting an OpenGL 4.3 context on Windows and linux. This apparently fails if OpenGL 4.3 is not supported instead of falling back to 3.1.
Either the core needs to retry initialization with a lower OpenGL version or the frontend needs to be updated to fall back to a lower level.

**Comment by hostile1975** [comment]
so, its exactlely contrary of what I said

**Comment by inactive123** [comment]
It should not always try to request a GL 4.3 context. This should be dependent on whether alpha sorting is set to ‘per pixel’.

**Comment by flyinghead** [comment]
Yes but  switching from/to per-pixel can be done without restarting the core. For this to be possible, you need a 4.3 context right from the start.

**Comment by inactive123** [comment]
OK, if setting up a 4.3 core context fails, we should recursively attempt to set up a GL3 context. That fails as well, opt for GL 2.x, and so on.

Let me see if I can push the necessary changes to GLSM to allow for this.

**Comment by inactive123** [comment]
Hopefully this will solve your problem @blackman91  -

https://github.com/libretro/reicast-emulator/commit/8cde4ab0f81553f3883bc9665f7017a2d729a39a

**Comment by inactive123** [comment]
Is it fixed now @blackman91 ?

**Comment by blackman91** [comment]
Just had a chance to test again but it is still crashing after updating the core, I even removed all my core remaps and options remaps, using Retroarch latest nightly too:

[INFO] 	DEFAULT_OFF 01
[libretro INFO] File extension is: .gdi
[INFO] Environ SET_HW_RENDER.
[INFO] Requesting core OpenGL context (4.3).
[INFO] Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 44055.95 Hz.
[INFO] [Video]: Video @ 1920x1440
[INFO] [Video]: Using HW render, OpenGL driver forced.
[INFO] [GL]: Found GL context: wgl
[INFO] [GL]: Detecting screen resolution 1600x900.
[ERROR] [WGL]: Failed to create core context. Falling back to legacy context.
[INFO] [WGL] extensions: WGL_EXT_depth_float WGL_ARB_buffer_region WGL_ARB_extensions_string WGL_ARB_make_current_read WGL_ARB_pixel_format WGL_ARB_pbuffer WGL_EXT_extensions_string WGL_EXT_swap_control WGL_EXT_swap_control_tear WGL_ARB_multisample WGL_ARB_pixel_format_float WGL_ARB_framebuffer_sRGB WGL_ARB_create_context WGL_EXT_pixel_format_packed_float 
[INFO] [WGL]: Adaptive VSync supported.
[INFO] [WGL]: wglSwapInterval(1)
[INFO] [GL]: Vendor: Intel, Renderer: Intel(R) HD Graphics 3000.
[INFO] [GL]: Version: 3.1.0 - Build 9.17.10.4229.
[INFO] [GL]: Using Core GL context, setting up VAO...
[INFO] [GL]: Using resolution 1604x820
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 430.
[INFO] Shader log: ERROR: 0:1: '' :  Version number not supported by OGL driver
ERROR: 3:1: 'in' :  supported in GLSL 1.30 or later 
ERROR: 3:1: 'in' :  supported in GLSL 1.30 or later 
ERROR: 3:1: 'in' :  supported in GLSL 1.30 or later 
ERROR: 3:1: 'out' :  supported in GLSL 1.30 or later 


[ERROR] Failed to compile vertex shader #0
[ERROR] Failed to link program #0.
[ERROR] GLSL stock programs failed to compile.
[ERROR] [GL]: Failed to initialize shader, falling back to stock.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 430.
[INFO] Shader log: ERROR: 0:1: '' :  Version number not supported by OGL driver
ERROR: 3:1: 'in' :  supported in GLSL 1.30 or later 
ERROR: 3:1: 'in' :  supported in GLSL 1.30 or later 
ERROR: 3:1: 'in' :  supported in GLSL 1.30 or later 
ERROR: 3:1: 'out' :  supported in GLSL 1.30 or later 


[ERROR] Failed to compile vertex shader #0
[ERROR] Failed to link program #0.
[ERROR] GLSL stock programs failed to compile.
[ERROR] [GL]: Shader initialization failed.
[ERROR] [Video]: Cannot open video driver ... Exiting ...
[ERROR] Fatal error received in: "init_video()"
[ERROR] failed_to_start_audio_driver
[libretro INFO] Using Recompiler

**Comment by inactive123** [comment]
@flyinghead Can you take it from here? We definitely cannot require that the GL driver supports at least 4.3  from now on, it should still be backwards compatible with older GPUs/drivers as well.

**Comment by inactive123** [comment]
@blackman91 @flyinghead Came up with this proposed solution -

https://github.com/libretro/RetroArch/commit/509ecab3fe75f286881270a5d4c1ba4d3e75ba66

You either need to compile from source or wait for the latest RetroArch nightly to compile that will be based on either this version or a later version.

![image](https://user-images.githubusercontent.com/1075274/46612658-7b668900-cb11-11e8-9e50-06d4190511eb.png)


If you go to Information -> Sy stem Information, this tells the Git hash the version was built on.

**Comment by blackman91** [comment]
Tested latest nightly and now it is working, in the core options still says per pixel as default but it still runs. Thanks a lot, great job.

**Comment by blackman91** [comment]
Did that brake something else? I see it has been reverted?
