### ISSUE TITLE
Dolphin blue atomiswave freeze on the same spot 

### ISSUE THREAD

**Issue by Tiganjos** [libretro/flycast#450]
Dolphin blue mame or naomiswave freeze on the same spot every time

**Comment by Tiganjos** [comment]
I am using android phone

**Comment by barbudreadmon** [comment]
What spot ? Some precision would be appreciated. 
Also, i don't think this game is currently fully playable (iirc there is an issue in a later stage)

**Comment by Tiganjos** [comment]
Yes on a final stage

**Comment by barbudreadmon** [comment]
Known issue then, however it's interesting to know that it's happening on different archs, that means the issue is probably unrelated to the SH4 interpreters.

**Comment by blisstik** [comment]
@Tiganjos - could you upload the save state right before it freezes?

**Comment by newoski** [comment]
Is the Naoimiwave conversion fully playable?

**Comment by tabnk** [comment]
Does it happen on Windows too?

**Comment by ghost** [comment]
Here the savestate of the spot!

https://www38.zippyshare.com/v/mtOsL73Z/file.html

PS: Special thanks to @skmp,  @flyinghead and All other Developers.

With the latest builds, the threaded Reicast core setting, work very well on my Android! :D

**Comment by cubatilles** [comment]
Is this issue even being looked at? Dolphin Blue is one of my favourites on the system and would love to be able to play it until the end.

**Comment by blisstik** [comment]
@stizzo1 - I tried the savestate on the XU4 and it would just crash upon load. Is it supposed to load a portion of the game first then go to a specific spot to crash?

**Comment by ghost** [comment]
@6alileo,

I think the problem is just the dump of the game, it's a bad dump.

**Comment by cubatilles** [comment]
But the problem only happens on reicast. It does not happen on demul. Indeed, I successfully finished the game on demul this last weekend on a friends' home.

**Comment by newoski** [comment]
Does it happen with both  MAME and bin/lst versions?

**Comment by flyinghead** [comment]
It does happen with the MAME dump

**Comment by newoski** [comment]
How about bin/lst?

**Comment by barbudreadmon** [comment]
@newoski it happens with both

@flyinghead i can't find the message, but i remember @p1pkin mentioned something about aica emulation about this game ? do you think this issue is related ?

**Comment by p1pkin** [comment]
@barbudreadmon right, in old demul versions this game became silent near end of stage 1 - start of stage 2, it was fixed after AICA rewrite. but I'm not sure if its the cause here too.

also, it is not recommended to use "bin/lst" versions, which is homebrew AW-to-Naomi ports made by Joerg & Darksoft, and in general is quite ugly piece of hacks.

**Comment by emersonnovais** [comment]
I have the same error with the second stage using .lst/.bin in Ubuntu 18.04 64 bits. As I still the error from terminal and the core doesn't load the Reicast core with Retroarch interface, I cann't test the lMAME rom.
¯\_(ツ)_/¯

**Comment by flyinghead** [comment]
This is because the .bin is corrupted / hacky. You should use MAME roms zip files instead.

**Comment by emersonnovais** [comment]
I tested the MAME rom version and crashs and the same point.
EDIT: The last update (04/12/2019) make Blue Dolphin of MAME rom works, but now crashes on the begining of the last stage,

**Comment by dukeblooders** [comment]
I've played the game today and I had a freeze followed by a restart of the core (to Atomiswave logo, without exiting Retroarch). At 8:50 on this video (not mine of course) :
https://www.youtube.com/watch?v=o_hBKCy2Ntg

I'm playing on Windows with latest nigthly build.

**Comment by dukeblooders** [comment]
Game also crashes sometimes on 2nd mission (2nd part just before the tank). And the game restarts to Sammy/Atomiswave logo without exiting RA (Windows 10)

Log file :
[output.txt](https://github.com/libretro/flycast/files/3363653/output.txt)

**Comment by eadmaster** [comment]
with the latest build it does not freeze, but i get stuck at this point (the stage does not scroll):
![dolphin-200530-212216_scaled](https://user-images.githubusercontent.com/925171/83337477-020a4400-a2bc-11ea-8890-f3d1e6a9c3d6.png)

Any workaround i can try?

EDIT: savestate: [dolphin.state1.zip](https://github.com/libretro/flycast/files/4706299/dolphin.state1.zip)

**Comment by daninthemix** [comment]
What's the current status? I encountered the freeze on the last stage, so I save stated beforehand then updated the core to 3be6f8f, loaded the save and it still freezes.

**Comment by flyinghead** [comment]
No progress on this bug

**Comment by Sanaki** [comment]
Just verified it wasn't related to a bad rom and wasn't accidentally fixed at some point. Still freezes during final stage on 8f3fd1f. I've also attached a state from beforehand, just in case, but I'd imagine this is of no significant help.
[dolphin.state1.zip](https://github.com/libretro/flycast/files/5587786/dolphin.state1.zip)

ROM was verified against MAME 0.226.

**Comment by Alextended** [comment]
Used to freeze for me a few seconds in the first level, around where the first tank appears, but it seems fixed as of today.

Checked to see if it changed anything for samurai spirits tenkaichi kenkakuden as well but nope, that one still has weird layers.

**Comment by emersonnovais** [comment]
@Sanaki same case here. I had the same problem with Dolphin Blue's Atomiswave port with all bug fixeds. It crashes to me in the same point.

**Comment by Drenuja** [comment]
Same here, tried it with Atomiswave, with Naomi, with the port made by fans on the dreamcast. It ALWAYS crashs a few seconds after the beginning of the last stage.

**Comment by n33k33** [comment]
Just experienced the very same thing:

> with the latest build it does not freeze, but i get stuck at this point (the stage does not scroll):
> ![dolphin-200530-212216_scaled](https://user-images.githubusercontent.com/925171/83337477-020a4400-a2bc-11ea-8890-f3d1e6a9c3d6.png)
> 
> Any workaround i can try?
> 
> EDIT: savestate: [dolphin.state1.zip](https://github.com/libretro/flycast/files/4706299/dolphin.state1.zip)

**Comment by flyinghead** [comment]
Fixed in standalone by this commit https://github.com/flyinghead/flycast/commit/b3de6a166df68e972d3bed44d25806123b773673

**Comment by cubatilles** [comment]
Thanks @flyinghead, you're the man!

I guess we'll see the fix committed to the libretro port sooner than later.

Thanks for your hard work on dreamcast opensource emulation.

Greetings!

**Comment by Drenuja** [comment]
Hello @flyinghead , unfortunately this bug is still here. Can you update your fix please ?

Thanks for al your work.

**Comment by Sanaki** [comment]
It hasn't been merged into the core yet. It will be in time, presumably when someone has time to deal with it.

**Comment by Alextended** [comment]
I honestly do not have this issue for a long while now (since January 10 that I mentioned it in this thread) so I dunno what to tell you since you say it's not yet fixed in the core, is my PC magic? It used to happen in stage one around when you encounter the first tank just before hitting the water but I've now gone up to level 4 with no issues. Is the crash point further in the game for you? Is anyone maybe using those recent atomiswave-to-dreamcast ports instead of just emulate atomiswave? Cos I did that inititally but I can't 100% recall if for me it was solved when I switched to standard atomiwave roms and emulation. I chalked it up to core updates.

**Comment by Sanaki** [comment]
> Is the crash point further in the game for you?

Read above. It's at the beginning of the final stage. And it's a freeze rather than a crash.

**Comment by Drenuja** [comment]
> 
> 
> I honestly do not have this issue for a long while now (since January 10 that I mentioned it in this thread) so I dunno what to tell you since you say it's not yet fixed in the core, is my PC magic? It used to happen in stage one around when you encounter the first tank just before hitting the water but I've now gone up to level 4 with no issues. Is the crash point further in the game for you? Is anyone maybe using those recent atomiswave-to-dreamcast ports instead of just emulate atomiswave? Cos I did that inititally but I can't 100% recall if for me it was solved when I switched to standard atomiwave roms and emulation. I chalked it up to core updates.

Well if you play the first 10 minutes of each game you play you won't find many issues ^^". The game crash in the beginning of the last stage. The game freezes but the sounds still runs on making the game impossible to complete. It crashes with the Atomiswave rom AND it also crashes with the fan made dreamcast port. Try completing the game (around 35-40 minutes) and you'll see.
