### ISSUE TITLE
Service/Test mode exit crashes and atomiswave games not saving

### ISSUE THREAD

**Issue by ziltama** [libretro/flycast#502]
Cannot save settings in Atomiswave games after exiting service / test mode. Get a warning about data being erased upon game boot. 

Many non-Atomiswave games have a problem where Reicast hangs when trying to exit the service / test mode. Have to exit the core and then restart.

**Comment by flyinghead** [comment]
This should be fixed now. Please retest.

**Comment by ziltama** [comment]
Thanks a lot. Not sure if what I downloaded through core updater is the latest version. Downloaded core on 3-27-2019.

Edit: version 0.1 50e733b

Atomiswave saving now works on the games I tested: samurai shodown vi, metal slug 6, king of fighters xi, and neogeo battle coliseum (ngbc still has a lot of graphical glitches). Now the games can be set to English.

Samurai Shodown VI now has a problem where after exiting test mode, the game would hang on the loading screen (grey screen with a multi-colored horizontal bar). The other atomiswave games I tested didn't do this. I would have to exit retroarch and restart. Saving is not affected.

There's some Naomi games that still hang on exit from test mode: Cannon Spike, Sega Tetris, Mobile Suit Gundam, Power Stone 2, Marvel vs Capcom 2, and Capcom vs SNK 2.

Street Fighter Zero 3 Upper, Psyvariar 2, Spawn, and Giga Wing 2 do not hang for me when exiting test mode.

**Comment by blisstik** [comment]
@ziltama - if you are using RetroPie, you can get the saved nvmem and eeprom files by going into the test menu, change the settings then exit out of the core via SELECT + START without doing a save on the test menu, it will still create the files that saved those settings.

I also have them archived here.
https://github.com/Retro-Arena/binaries/raw/master/odroid-xu4/Reipack.zip

**Comment by flyinghead** [comment]
Assuming this is resolved. Reopen as needed

**Comment by Denshadego** [comment]
Still hangs after exiting test mode on Atomiswave games. On Naomi only hangs if the game has been fully loaded (after the Naomi logo), if the test mode has been entered during the startup logo animation , you can exit safely. This is not the case on atomiswave, where it hangs every time you exit .

**Comment by flyinghead** [comment]
@demodanza I just tested like 7 Atomiswave games and they all reboot fine when exiting the service menu. Please open a new issue with more details: game name/format, logs...

Naomi reboot is still a problem iirc.

**Comment by ani917** [comment]
> Atomiswave saving now works on the games I tested: samurai shodown vi, metal slug 6, king of fighters xi, and neogeo battle coliseum (ngbc still has a lot of graphical glitches). Now the games can be set to English.

To get to this menu, do you need to click "Service" at the beginning game? I can't figure it out; it doesn't work for me! I also confirm that there are still graphical artifacts in the colosseum
