### ISSUE TITLE
Headhunter glitches and crashes

### ISSUE THREAD

**Issue by dukeblooders** [libretro/flycast#563]
Hi,

1. The game crashes when I use a Continue (not always, but very often [output.txt]) or when I cancel a save load (B button on the vmus screen [output2.txt]). This can be tested with my save in the room where the player starts (disc 2).

2. **Fixed** : The radar is not displayed (I see it, but not the map inside). 

3. **Fixed** : The sound, in certain cinematics, repeats itself almost at same time (for example, at the hospital, at the beginning of the game, after the lab escape)

I use :
- Alpha sorting : per pixel
- Vmu per game : A1
- Region : Europe (PAL version of the game)
- Language : French
- Other options by default 

Are those bugs or just a bad configuration ?

Beside this, the game works like a charm. Thanks for the hard work.

[output2.txt](https://github.com/libretro/flycast/files/3277894/output2.txt)
[output.txt](https://github.com/libretro/flycast/files/3277895/output.txt)
[Headhunter.A1.zip](https://github.com/libretro/flycast/files/3278512/Headhunter.A1.zip)

**Comment by flyinghead** [comment]
I did a quick test on the vmu screen and I was able to crash the game quite easily by pressing B.
This is with upstream reicast so it's not related to the libretro core.
It seems to be an audio issue where it's decoding past the end of the audio ram.

**Comment by dukeblooders** [comment]
Ok thanks for your reply (guess I have to open an issue on reicast ?)

**Comment by flyinghead** [comment]
No need to open an issue upstream. I have a fix already that I'll push later today.

I also confirm the radar map is empty. No idea why yet.

Regarding the turbo mode issue I would think it's a RetroArch button binding issue. Double check the RA input settings.

**Comment by dukeblooders** [comment]
Thanks for your feedback.

**Comment by dukeblooders** [comment]
I just tested the last nighlty with the WinCE core, the crashes are gone. Thanks for your work

**Comment by flyinghead** [comment]
The map/radar issue should be fixed by https://github.com/libretro/flycast/commit/ee30a90bceba765245f126cb0229d3edb1b710fb
Note that it only happened with per-pixel sorting. The map was rendered normally in per-triangle and per-strip modes.

**Comment by dukeblooders** [comment]
Hi, yes indeed, that works fine now. Thanks.
However, the vmu or continue crashes are still present. I thougt that was good because your previous patch fixes a game breaking bug I didn't mention (I thought it was related to these ones).
But, at least, the game can be finished now.

[output.txt](https://github.com/libretro/flycast/files/3374088/output.txt)

**Comment by flyinghead** [comment]
Yes, my bad: the audio crash fix I mentioned earlier only works on 64-bit linux and android right now. I'll spare you the boring technical details but I still need to come up with a fix for windows and 32-bit platforms.

**Comment by flyinghead** [comment]
The audio crash fix should now work on all platforms

**Comment by dukeblooders** [comment]
Tested and works perfectly. Awesome ! Thx
