### ISSUE TITLE
Lightgun Crosshair doesn't show on Naomi games.

### ISSUE THREAD

**Issue by r3tro80** [libretro/flycast#600]
The lightgun crosshair works only on Dreamcast games but not on Naomi games.

**Comment by flyinghead** [comment]
Fixed on the WinCE core: https://github.com/libretro/flycast/commit/5ceffc3ea2c1ba600ba8524adcd73063917e5777

**Comment by r3tro80** [comment]
Still cannot test it! Retroarch core is 2 commits behind and i don't know how to compile this commit on RetroPie. Will the wince branch be merged into master soon?

**Comment by flyinghead** [comment]
In `RetroPie-Setup/scriptmodules/libretrocores/lr-flycast.sh`, add `fh/wince` to the line that starts with `gitPullOrClone`:
```
    gitPullOrClone "$md_build" https://github.com/libretro/flycast.git fh/wince
```

**Comment by r3tro80** [comment]
Wow thank you!! I already tried but i added "wince" only at the end of that
line without the "fh/".

I will test it later thanks!!

Il giorno ven 13 set 2019 alle ore 16:07 flyinghead <
notifications@github.com> ha scritto:

**Comment by flyinghead** [comment]
Unfortunately it's more complicated than that because the wince core file name is different. That's why I deleted my earlier comment. I don't want you to mess up your system.

**Comment by r3tro80** [comment]
Yes i see that compiling the wince branch creates a "flycast_wince_libretro.so" file instead of the one required by the script, anyway i renamed it and tried but i wasn't able to see any gunsight, which options must be enabled to see the gunsight? I enabled the gunsight in options and i selected the hle bios too...

**Comment by r3tro80** [comment]
I managed to work the gunsight using retroarch and latest commit compiled core...

The gunsight is displayed and it moves but the effective pointer is stuck at the upper left corner.

Here you can download a video of the bug: https://we.tl/t-AoztxX9WPP

**Comment by flyinghead** [comment]
Did you set your controller to "Light Gun"?

PS: The WinCE branch has been merged into master

**Comment by r3tro80** [comment]
I have the same problem, gunsight moves but aim stuck at upper left.

Anyway when i select lightgun i can't use any other buttons on same player, like coin or start... I suppose this control type needs some further tuning.

**Comment by flyinghead** [comment]
Assuming this is resolved. Reopen as needed
