### ISSUE TITLE
Vampire Chronicle Crash

### ISSUE THREAD

**Issue by Denshadego** [libretro/flycast#669]
Using RA on Android, Flycast crashes RA after the Sega screen, where it was working fine a couple weeks ago. Happens with Vampire Chronicle for Matching Service (Japan) and Super Puzzle Fighter II.

**Comment by flyinghead** [comment]
Good catch! It's an arm64 dynarec issue. Same problem for both games.

**Comment by flyinghead** [comment]
Should be fixed by https://github.com/libretro/flycast/pull/671

**Comment by litaniast** [comment]
I used latest version in RockPro64 (32bit version), but SSF2X and Vampire Chronicle still crash after the Sega logo

**Comment by flyinghead** [comment]
This commit 0643e6ac705cee3965710881ede43c7821ef4df2 should fix it on arm32

**Comment by flyinghead** [comment]
Assuming this is fixed. Re-open if not
