### ISSUE TITLE
Soulcalibur - glitches in intro

### ISSUE THREAD

**Issue by mlnlbrt** [libretro/flycast#94]
Seems that ground texture is broken in Soulcalibur intro:

![41475329-ceae79a4-70be-11e8-97fe-1754586d0a61](https://user-images.githubusercontent.com/11428910/42136130-5e0ae3fa-7d56-11e8-900f-205e366b4556.png)
![41475339-d6452e56-70be-11e8-9741-0d5bf6522f2b](https://user-images.githubusercontent.com/11428910/42136132-631f3e36-7d56-11e8-9a59-8b9bcee44ec1.png)

**Comment by inactive123** [comment]
This only happens on Nvidia. I tried it on an Intel HD 4K and it renders fine there.

Must be some kind of GLSL shader bug specific only to NV.

**Comment by flyinghead** [comment]
This is caused by some primitives that have infinite Z value. Apparently some drivers/GPUs don't like that. I was able to reproduce it on my Macbook (NVidia GT 750M)
This should fix it: https://github.com/reicast/reicast-emulator/commit/b1686a8f6a96036d5b4b4e18859bbb19b7859314

**Comment by inactive123** [comment]
Hmm, the issue still happens for me on Reicast OIT with an Nvidia Titan XP (Windows 10).

**Comment by inactive123** [comment]
Same with the non-OIT core. I will backport the commit for now though.

**Comment by flyinghead** [comment]
You might want to try a bigger number than the one I used(`1.18e-38`). For example: `1e-6`

**Comment by inactive123** [comment]
Tried it, same issue unfortunately.

**Comment by orbea** [comment]
This occurs with nouveau too, its not only the nvidia blob.

**Comment by orbea** [comment]
It doesn't occur with the llvmpipe however.

**Comment by orbea** [comment]
@flyinghead Apitrace reveals several major api errors when replaying traces with the llvmpipe. For some reasons these errors do not show up when replayed with nouveau, instead the graphics are broken.

For example.
```
10732: message: major api error 1: GL_INVALID_ENUM in glActiveTexture(texture=GL_MAX_VERTEX_ARRAY_RANGE_ELEMENT_NV)
10732 @0 glActiveTexture(texture = GL_MAX_VERTEX_ARRAY_RANGE_ELEMENT_NV)
10732: warning: glGetError(glActiveTexture) = GL_INVALID_ENUM
10734: message: major api error 1: GL_INVALID_ENUM in glActiveTexture(texture=GL_VERTEX_ARRAY_RANGE_POINTER_APPLE)
10734 @0 glActiveTexture(texture = GL_VERTEX_ARRAY_RANGE_POINTER_NV)
10734: warning: glGetError(glActiveTexture) = GL_INVALID_ENUM
10736: message: major api error 1: GL_INVALID_ENUM in glActiveTexture(texture=GL_REGISTER_COMBINERS_NV)
10736 @0 glActiveTexture(texture = GL_REGISTER_COMBINERS_NV)
10736: warning: glGetError(glActiveTexture) = GL_INVALID_ENUM
10738: message: major api error 1: GL_INVALID_ENUM in glActiveTexture(texture=GL_VARIABLE_A_NV)
10738 @0 glActiveTexture(texture = GL_VARIABLE_A_NV)
10738: warning: glGetError(glActiveTexture) = GL_INVALID_ENUM
10740: message: major api error 1: GL_INVALID_ENUM in glActiveTexture(texture=GL_VARIABLE_B_NV)
10740 @0 glActiveTexture(texture = GL_VARIABLE_B_NV)
10740: warning: glGetError(glActiveTexture) = GL_INVALID_ENUM
```
Full log - https://pastebin.com/8cS1Yu8S

The trace can be found here.

http://0x0.st/st9G.xz

**Comment by orbea** [comment]
With help from nouveau developers the first bad call In the above trace is `11126` which is `glDrawElements(GL_TRIANGLE_STRIP, 2376,GL_UNSIGNED_SHORT,0x20)`.

This patch fixes it for nouveau (And maybe nvidia?), but introduces it for the llvmpipe instead.
```
diff --git a/core/rend/gles/gles.cpp b/core/rend/gles/gles.cpp
index 0f4e5dba..d92129c8 100644
--- a/core/rend/gles/gles.cpp
+++ b/core/rend/gles/gles.cpp
@@ -91,8 +91,8 @@ void main() \n\
        vtx_uv=in_uv; \n\
        vec4 vpos=in_pos; \n\
 #if TARGET_GL != GLES2 && TARGET_GL != GL2 \n\
-   if (isinf(vpos.z)) \n\
-               vpos.w = 1.18e-38; \n\
+   if (abs(vpos.z) > 1.0e10) \n\
+               vpos.w = 1.18e-10; \n\
        else \n\
 #endif \n\
                vpos.w = 1.0 / vpos.z; \n\
```
Note that setting the exponent to either `9` or `11` instead of `10` only partially fixes it for nouveau.

Here are the shaders from qapitrace.

GL_FRAGMENT_SHADER
```
#version 130 
#define TARGET_GL GL3 

#define cp_AlphaTest 0 
#define pp_ClipTestMode 0 
#define pp_UseAlpha 1 
#define pp_Texture 1 
#define pp_IgnoreTexA 0 
#define pp_ShadInstr 3 
#define pp_Offset 1 
#define pp_FogCtrl 1 
#define pp_Gouraud 1 
#define pp_BumpMap 0 
#define PI 3.1415926 

#define GLES2 0 
#define GLES3 1 
#define GL2 2 
#define GL3 3 
 
#if TARGET_GL == GL2 
#define highp 
#define lowp 
#define mediump 
#endif 
#if TARGET_GL == GLES3 
out highp vec4 FragColor; 
#define gl_FragColor FragColor 
#define FOG_CHANNEL a 
#elif TARGET_GL == GL3 
out highp vec4 FragColor; 
#define gl_FragColor FragColor 
#define FOG_CHANNEL r 
#else 
#define in varying 
#define texture texture2D 
#define FOG_CHANNEL a 
#endif 
 
 
#if TARGET_GL == GL3 || TARGET_GL == GLES3 
#if pp_Gouraud == 0 
#define INTERPOLATION flat 
#else 
#define INTERPOLATION smooth 
#endif 
#else 
#define INTERPOLATION 
#endif 

/* Shader program params*/ 
/* gles has no alpha test stage, so its emulated on the shader */ 
uniform lowp float cp_AlphaTestValue; 
uniform lowp vec4 pp_ClipTest; 
uniform lowp vec3 sp_FOG_COL_RAM,sp_FOG_COL_VERT; 
uniform highp float sp_FOG_DENSITY; 
uniform sampler2D tex,fog_table; 
uniform lowp float trilinear_alpha; 
/* Vertex input*/ 
INTERPOLATION in lowp vec4 vtx_base; 
INTERPOLATION in lowp vec4 vtx_offs; 
in mediump vec2 vtx_uv; 
lowp float fog_mode2(highp float w) 
{ 
   highp float z   = clamp(w * sp_FOG_DENSITY, 1.0, 255.9999); 
   highp float exp = floor(log2(z)); 
   highp float m = z * 16.0 / pow(2.0, exp) - 16.0; 
   lowp float idx = floor(m) + exp * 16.0 + 0.5; 
   highp vec4 fog_coef = texture(fog_table, vec2(idx / 128.0, 0.75 - (m - floor(m)) / 2.0)); 
   return fog_coef.FOG_CHANNEL; 
} 
void main() 
{ 
	// Clip outside the box 
	#if pp_ClipTestMode==1 
		if (gl_FragCoord.x < pp_ClipTest.x || gl_FragCoord.x > pp_ClipTest.z 
				|| gl_FragCoord.y < pp_ClipTest.y || gl_FragCoord.y > pp_ClipTest.w) 
			discard; 
	#endif 
	// Clip inside the box 
	#if pp_ClipTestMode==-1 
		if (gl_FragCoord.x >= pp_ClipTest.x && gl_FragCoord.x <= pp_ClipTest.z 
				&& gl_FragCoord.y >= pp_ClipTest.y && gl_FragCoord.y <= pp_ClipTest.w) 
			discard; 
	#endif 
	
   lowp vec4 color=vtx_base; 
	#if pp_UseAlpha==0 
		color.a=1.0; 
	#endif
	#if pp_FogCtrl==3 
		color=vec4(sp_FOG_COL_RAM.rgb,fog_mode2(gl_FragCoord.w)); 
	#endif
	#if pp_Texture==1 
	{ 
      lowp vec4 texcol=texture(tex, vtx_uv); 
		 
		#if pp_BumpMap == 1 
			highp float s = PI / 2.0 * (texcol.a * 15.0 * 16.0 + texcol.r * 15.0) / 255.0; 
			highp float r = 2.0 * PI * (texcol.g * 15.0 * 16.0 + texcol.b * 15.0) / 255.0; 
			texcol.a = clamp(vtx_offs.a + vtx_offs.r * sin(s) + vtx_offs.g * cos(s) * cos(r - 2.0 * PI * vtx_offs.b), 0.0, 1.0); 
			texcol.rgb = vec3(1.0, 1.0, 1.0);	 
		#else
			#if pp_IgnoreTexA==1 
				texcol.a=1.0;	 
			#endif
         color *= trilinear_alpha; 
			
			#if cp_AlphaTest == 1 
				if (cp_AlphaTestValue>texcol.a) discard;
			#endif  
		#endif 
      #if pp_ShadInstr==0 
      { 
         color=texcol; 
      } 
      #endif
		#if pp_ShadInstr==1 
		{ 
			color.rgb*=texcol.rgb; 
			color.a=texcol.a; 
		} 
		#endif
		#if pp_ShadInstr==2 
		{ 
			color.rgb=mix(color.rgb,texcol.rgb,texcol.a); 
		} 
		#endif
		#if  pp_ShadInstr==3 
		{ 
			color*=texcol; 
		} 
		#endif
		
		#if pp_Offset==1 && pp_BumpMap == 0 
		{ 
			color.rgb+=vtx_offs.rgb; 
			if (pp_FogCtrl==1) 
				color.rgb=mix(color.rgb,sp_FOG_COL_VERT.rgb,vtx_offs.a); 
		} 
		#endif
	} 
	#endif
	#if pp_FogCtrl==0 
	{ 
		color.rgb=mix(color.rgb,sp_FOG_COL_RAM.rgb,fog_mode2(gl_FragCoord.w));  
	} 
	#endif
	#if cp_AlphaTest == 1 
      color.a=1.0; 
	#endif  
   //color.rgb=vec3(gl_FragCoord.w * sp_FOG_DENSITY / 128.0);
#if TARGET_GL != GLES2 
	highp float w = gl_FragCoord.w * 100000.0; 
	gl_FragDepth = log2(1.0 + w) / 34.0; 
#endif 
   gl_FragColor =color; 
}
```
GL_VERTEX_SHADER
```
#version 130 
#define TARGET_GL GL3 
#define pp_Gouraud 1 
 
#define GLES2 0 
#define GLES3 1 
#define GL2 2 
#define GL3 3 
 
#if TARGET_GL == GL2 
#define highp 
#define lowp 
#define mediump 
#endif 
#if TARGET_GL == GLES2 || TARGET_GL == GL2 
#define in attribute 
#define out varying 
#endif 
 
 
#if TARGET_GL == GL3 || TARGET_GL == GLES3 
#if pp_Gouraud == 0 
#define INTERPOLATION flat 
#else 
#define INTERPOLATION smooth 
#endif 
#else 
#define INTERPOLATION 
#endif 

/* Vertex constants*/  
uniform highp vec4      scale; 
uniform highp vec4      depth_scale; 
/* Vertex input */ 
in highp vec4    in_pos; 
in lowp  vec4     in_base; 
in lowp vec4     in_offs; 
in mediump vec2  in_uv; 
/* output */ 
INTERPOLATION out lowp vec4 vtx_base; 
INTERPOLATION out lowp vec4 vtx_offs; 
              out mediump vec2 vtx_uv; 
void main() 
{ 
	vtx_base=in_base; 
	vtx_offs=in_offs; 
	vtx_uv=in_uv; 
	vec4 vpos=in_pos; 
#if TARGET_GL != GLES2 && TARGET_GL != GL2 
   if (isinf(vpos.z)) 
		vpos.w = 1.18e-38; 
	else 
#endif 
		vpos.w = 1.0 / vpos.z; 
#if TARGET_GL != GLES2 
   if (vpos.w < 0.0) { 
      gl_Position = vec4(0.0, 0.0, 0.0, vpos.w); 
         return; 
   } 
   vpos.z = vpos.w; 
#else 
   vpos.z=depth_scale.x+depth_scale.y*vpos.w;  
#endif 
	vpos.xy=vpos.xy*scale.xy-scale.zw;  
	vpos.xy*=vpos.w;  
	gl_Position = vpos; 
}
```

**Comment by inactive123** [comment]
Interesting, so basically the solution is avoiding isinf then? @flyinghead What do you think about this?

**Comment by orbea** [comment]
Its not a perfect solution and the exponent number requires a sweet spot, in my case that is `10`.

The biggest potential problem is that it will fix it for nouveau and maybe nvidia while introducing the issue for other drivers... I suppose its relying on undefined behavior and different drivers react differently...

**Comment by flyinghead** [comment]
The `isinf` call was added to fix this issue in the Soulcalibur intro. If it breaks more things that it solves it would be better to get rid of it.
What’s unclear is why it’s breaking things and why it’s invalid.

**Comment by orbea** [comment]
Your fix didn't seem to cause any problems for me, just it didn't fix them either. Unfortunately I can't help much here except for spending time testing and debugging with tools like apitrace. Since this affects nouveau and nvidia, but not intel or the llvmpipe it possible the nouveau developers could help more especially if they talk to someone who understands this code better than me...

**Comment by flyinghead** [comment]
Yeah I was somewhat mixing this issue with another one. I guess some more investigation is needed.

**Comment by inactive123** [comment]
Works great and finally fixes this issue for me. It also fixes the other issues that happened with Soul Calibur.

https://github.com/libretro/reicast-emulator/commit/8f5706bbbae3f79d5525bf6d94753aba70ebef18

**Comment by orbea** [comment]
Did this get tested with intel or AMD? It breaks the llvmpipe so I'm worried it might break other non-nvidia cards too, but I can't test that myself...

**Comment by inactive123** [comment]
I didn't test it on AMD or Intel yet. Try testing it I guess on those.

**Comment by gouchi** [comment]
I tested on Intel HD 5500 and it is working correctly.

**Comment by mlnlbrt** [comment]
I confirm it is fixed. Tested on Linux + Nvidia binary drivers and GT1030 gpu.

Thanks! :)

**Comment by flyinghead** [comment]
Works fine on OS X with Nvidia 750M
